project:
  type: website
  pre-render:
    - python tools/extract_snippets.py
    - python tools/extract_rsnippets.py

website:
  title: "Testing in Research Workflows"
  favicon: images/stars_logo_blue.png
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/stars-testing-intro/
  announcement:
    dismissable: false
    icon: info-circle
    content: "This site contains materials for the testing module on HDR UK's RSE001 <a href='https://hdruklearn.org/courses/course-v1:HDRUK+RSE001+2024' target ='_blank'>Research Software Engineering training course</a>. It was developed as part of the <a href='https://pythonhealthdatascience.github.io/stars/' target='_blank'>STARS project</a>."
    position: below-navbar
  sidebar:
    contents:
      - pages/why_test.qmd
      - pages/case_study.qmd
      - section: Introduction to writing and running tests
        contents:
          - pages/write_basic_test.qmd
          - pages/run_tests.qmd
          - pages/parametrising_tests.qmd
          - pages/temp_mock.qmd
      - section: Types of test
        contents:
          - pages/smoke_tests.qmd
          - pages/unit_tests.qmd
          - pages/system_tests.qmd
          - pages/regression_tests.qmd
      - pages/break.qmd
      - pages/test_coverage.qmd
      - pages/github_actions.qmd
      - pages/defensive_programming.qmd
      - pages/example_repositories.qmd
  page-footer:
    center:
      - text: |
          Code licence: <a href="https://opensource.org/license/mit" target="_blank" rel="noopener">MIT</a>.  
          Text licence: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC-BY-SA 4.0</a>.

format:
  html:
    page-layout: full
    theme: [cosmo, assets/styles.scss]
    css:
      - assets/styles.css
      - assets/language-selector.css
    include-after-body: assets/language-selector.js
