name: hdruk_tests
channels:
  - conda-forge
dependencies:
  - flake8=7.3.0
  - lintquarto=0.7.0
  - numpy=2.4.1
  - pandas=2.3.3
  - pip=25.3
  - pylint=4.0.4
  - pytest=9.0.2
  - pytest-cov=7.0.0
  - python=3.12.12
  - scipy=1.17.0
  - pip:
     - -e examples/python_package/.