name: r_tests
run-name: Run R tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      RENV_CONFIG_PAK_ENABLED: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv from root
        run: |
          Rscript -e 'renv::restore(project = ".")'

      - name: Run testthat tests
        working-directory: examples/r_package
        run: |
          Rscript -e 'renv::activate(project = ".."); devtools::load_all(); testthat::test_dir("tests/testthat")'
